### ISSUE TITLE
Firefox 44.0.2 crashes when pressing "e"

### ISSUE THREAD

**Issue by rugk** [drumrollhq/E.A.K.#149] opened 2016-02-26 21:06 UTC
Firefox crashed when pressing "e" to show the edit area. However clicking on "edit" works fine.
I've submitted crash reports via Firefox Crash Reporter including the accessed site, so you should be able to find them.
I've added one with the following error message:
> Happens when pressing "E" to show edit box

Firefox 44.0.2 (stable)
Windows 7 x64

**Comment by rugk** [comment] 2016-02-26 21:23
Okay, just now it also happened when clicking on "edit" and not pressing "e". Probably it is just the first time I open the edit pane in a new level.

**Comment by SomeHats** [comment] 2016-02-29 11:50
Thanks for the report! The firefox crash reporter sends reports to Mozilla, not to me - so unfortunately I can't look at them.

I was able to reproduce the issue on the pilot on eraseallkittens.com, but not on the new version of the game that'll be released soon. Seeing as we're not doing any new work on the pilot version and I suspect this is an issue with Firefox, I'm marking this as wontfix. 

Feel free to try out the new version at staging.eraseallkittens.com - although remember that it's not finished yet! If you find this same issue there (I couldn't reproduce in the new version) please do open another issue :)

**Closed by SomeHats** 2016-02-29 11:50 UTC
Labels: Type: Wontfix

**Comment by rugk** [comment] 2016-02-29 18:40
> The firefox crash reporter sends reports to Mozilla, not to me - so unfortunately I can't look at them.

Well.. I think they're published somewhere...

But in current version I cannot reproduce the issues any more.
